var nameList = [
  "Ravi Patel",
  "Priya Sharma",
  "Vikram Gupta",
  "Neha Singh",
  "Aryan Kumar",
  "Kavita Joshi",
  "Sanjay Shah",
  "Anjali Verma",
  "Rahul Bhatt",
  "Sneha Chauhan",
  "Amit Patel",
  "Pooja Singh",
  "Aarav Mehta",
  "Radhika ",
  "Aditya Shah",
  "Shalini Gupta",
  "Rohan Kapoor",
  "Divya Sharma",
  "Manish Patel",
  "Shreya Singh",
  "Aakash Patel",
  "Ananya Gupta",
  "Rajiv ",
  "Kiran Patel",
  "Arjun Desai",
  "Tanvi Joshi",
  "Deepak Shah",
  "Ananya Reddy",
  "Saurabh Patel",
  "Sakshi Singh",
  "Vijay Kumar",
  "Nisha Rao",
  "Vivek",
  "Shweta Sharma",
  "Sid Patel",
  "Neha Gupta",
  "Rajesh Singh",
  "Kritika Joshi",
  "Gaurav Patel",
  "Anu Sharma",
  "Pranav Gupta",
  "Nidhi Singh",
  "Ankit Patel",
  "Jyoti Gupta",
  "Ashish",
  "Sonali Desai",
  "Raghav Patel",
  "Riya Singh",
  "Himanshu Shah",
  "Smita Verma",
  "Vishal Bhatt",
  "Payal Chauhan",
  "Nikhil Patel",
  "Aishwarya Singh",
  "Aryan ",
  "Shruti Patel",
  "Aarav Gupta",
  "Pallavi Mishra",
  "Kunal Shah",
  "Amrita Patel",
  "Rajat Sharma",
  "Shikha Gupta",
  "Mayank Patel",
  "Vidya Singh",
  "Arun Sharma",
  "Shweta Patel",
  "Satish Gupta",
  "Sneha Verma",
  "Vishnu Patel",
  "Sapna Sharma",
  "Amit Kumar",
  "Jaya Patel",
  "Yash Sharma",
  "Ritu Chauhan",
  "Karthik Patel",
  "Anjali Reddy",
  "Hitesh Kumar",
  "Swati Singh",
  "Raj Patel",
  "Roshni Gupta",
  "Nitin Sharma",
  "Renuka Patel",
  "Sandeep Singh",
  "Anamika Gupta",
  "Deepak Patel",
  "Preeti Sharma",
  "Siddharth",
  "Neha Patel",
  "Vijay Singh",
  "Shalini Gupta",
  "Alok Patel",
  "Kiran Singh",
  "Hari Sharma",
  "Shweta Verma",
];

export function generateRandomName() {
  return nameList[Math.floor(Math.random() * nameList.length)];
}
var commentList = [
  "Great tutorial! ",
  "Explain the process step by step, please.",
  "I have a question about the previous topic.",
  "Recommend additional learning resources?",
  "Struggling to implement in my project.",
  "Mind-blowing!",
  "Thanks for simplifying. Easier to grasp now.",
  "Tips for beginners in this field?",
  "Wish me luck!",
  "Can you share the code snippet used?",
  "Impressed by your expertise. ",
  "Exactly what I needed. ",
  "Love the interactive live sessions.",
  "More detailed explanation of the concept?",
  "Impressed by practical applications shown.",
  "Recommend beginner-friendly IDEs?",
  "Struggling with a bug.",
  " Thank you!",
  "Learning so much in the live stream.",
  "Future topics for live sessions?",
  "Demo in a real-world scenario, please.",
  "I want to learn more.",
  "Hwwwwwww",
  " So much valuable information!",
  "Grateful for your prepared live sessions.",
  "Highlight of my week!",
  "More live sessions on advanced topics, please.",
  " Thank you for being a mentor.",
  "Appreciate the clear examples provided.",
  "Recommended books for fundamentals?",
  "Finally understand! Thanks for the explanation.",
  "Looking forward to the next live session.",
  "Love it.",
  "Online courses that complement the topics?",
  "Appreciate the real-world examples provided.",
  "Your explanations are beginner-friendly.",
  "Thank you brother",
  "Hiii",
  "Hi",
  "Hello",
  "how are you all ?",
];

export function generateRandomChat() {
  return commentList[Math.floor(Math.random() * commentList.length)];
}
